spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.220.84:3306/shing_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:

    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1